### ISSUE TITLE
"medium only" behaviour

### ISSUE THREAD

**Issue by chris-dvlpr** [javipuche/mediaqueries-sass-mixin#1]
Hey Javier, 

Nice little mixin! I noticed however when I was using "medium only" the output was:

```
@include breakpoint(medium) {
}

Output:
@media screen and (min-width: 64em) and (max-width: 63.9375em) {
}
```
Which isn't how I expected it to work - not sure if this is an issue or something I'm doing wrong.

**Comment by javipuche** [comment]
Fixed ;)
